# Generated by Django 6.0.5 on 2026-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='01', max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('topic', models.CharField(default='general', max_length=100)),
                ('content_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived')], default='pending')),
                ('visible', models.BooleanField(default=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image2_url', models.URLField(blank=True, null=True)),
                ('image3_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('angular_questions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_angular',
            },
        ),
    ]
