# Generated by Django 6.0.5 on 2026-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='draft', max_length=20),
        ),
    ]
