# Generated by Django 6.0.5 on 2026-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0002_angular_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angular',
            name='status',
        ),
        migrations.AddField(
            model_name='angular',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='angular',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'InReview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='draft', max_length=50),
        ),
    ]
