# Generated by Django 6.0.5 on 2026-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0004_fill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='angular',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
