# Generated by Django 6.0.5 on 2026-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0005_alter_angular_created_at_alter_angular_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='content_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('in review', 'InReview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived'), ('completed', 'Completed'), ('in progress', 'InProgress')], default='draft', max_length=50),
        ),
    ]
