# Generated by Django 6.0.5 on 2026-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0006_alter_angular_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='code_block',
            field=models.TextField(blank=True, null=True),
        ),
    ]
