# Generated by Django 6.0.5 on 2026-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0007_angular_code_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='language',
            field=models.CharField(choices=[('angular', 'Angular'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence')], default='angular', max_length=50),
        ),
    ]
