# Generated by Django 6.0.5 on 2026-06-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0008_angular_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angular',
            name='category',
        ),
    ]
