# Generated by Django 6.0.5 on 2026-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0009_remove_angular_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='angular',
            name='language',
            field=models.CharField(choices=[('all', 'All'), ('angular', 'Angular'), ('javascript', 'JavaScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence')], default='angular', max_length=50),
        ),
    ]
