# Generated by Django 6.0.5 on 2026-06-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0010_angular_level_alter_angular_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('mastery', 'Mastery')], default='basic', max_length=20),
        ),
    ]
