# Generated by Django 6.0.5 on 2026-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0011_alter_angular_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angular',
            name='level',
        ),
        migrations.AddField(
            model_name='angular',
            name='label',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('mastery', 'Mastery')], default='basic', max_length=20),
        ),
    ]
