# Generated by Django 6.0.5 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0012_remove_angular_level_angular_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='code_block2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='code_block3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='angular',
            name='label',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('mastery', 'Mastery')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='angular',
            name='language',
            field=models.CharField(choices=[('angular', 'Angular'), ('javascript', 'JavaScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence'), ('question_design', 'Question Design')], default='angular', max_length=50),
        ),
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(default='angular', max_length=100),
        ),
    ]
