# Generated by Django 6.0.5 on 2026-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0013_angular_code_block2_angular_code_block3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='answer3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='answer4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
