# Generated by Django 6.0.5 on 2026-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0014_angular_answer3_angular_answer4'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='code_block_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='code_block_title2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='code_block_title3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
