# Generated by Django 6.0.5 on 2026-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0015_angular_code_block_title_angular_code_block_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='code_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='code_language2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='code_language3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
