# Generated by Django 6.0.5 on 2026-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0017_alter_angular_code_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='code_language',
            field=models.CharField(choices=[('html', 'Markup'), ('css', 'CSS'), ('typescript', 'Typescript'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
        migrations.AlterField(
            model_name='angular',
            name='code_language2',
            field=models.CharField(choices=[('html', 'Markup'), ('css', 'CSS'), ('typescript', 'Typescript'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
        migrations.AlterField(
            model_name='angular',
            name='code_language3',
            field=models.CharField(choices=[('html', 'Markup'), ('css', 'CSS'), ('typescript', 'Typescript'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
    ]
