# Generated by Django 6.0.5 on 2026-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0021_alter_angular_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(choices=[('angular_fundamentals', 'Angular Fundamentals'), ('components_templates', 'Components & Templates'), ('directives_pipes', 'Directives & Pipes'), ('dependency_injection', 'Dependency Injection & Services'), ('component_lifecycle', 'Component Lifecycle'), ('routing', 'Routing'), ('forms', 'Forms'), ('http', 'HTTP & APIs'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('state_management', 'State Management'), ('angular_material', 'Angular Material'), ('advanced_angular', 'Advanced Angular'), ('ssr_hydration', 'SSR & Hydration'), ('testing', 'Testing'), ('performance', 'Performance'), ('security', 'Security'), ('build_deployment', 'Build & Deployment'), ('angular_ecosystem', 'Angular Ecosystem'), ('expert_angular', 'Expert Angular')], default='routing', max_length=50),
        ),
    ]
