# Generated by Django 6.0.5 on 2026-06-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0022_alter_angular_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(choices=[('Angular Fundamentals', 'angular_fundamentals'), ('Components & Templates', 'components_templates'), ('Directives & Pipes', 'directives_pipes'), ('Dependency Injection & Services', 'dependency_injection'), ('Component Lifecycle', 'component_lifecycle'), ('Routing', 'routing'), ('Forms', 'forms'), ('HTTP & APIs', 'http'), ('RxJS', 'rxjs'), ('Signals', 'signals'), ('State Management', 'state_management'), ('Angular Material', 'angular_material'), ('Advanced Angular', 'advanced_angular'), ('SSR & Hydration', 'ssr_hydration'), ('Testing', 'testing'), ('Performance', 'performance'), ('Security', 'security'), ('Build & Deployment', 'build_deployment'), ('Angular Ecosystem', 'angular_ecosystem'), ('Expert Angular', 'expert_angular')], default='Routing', max_length=50),
        ),
    ]
