# Generated by Django 6.0.5 on 2026-06-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0026_alter_angular_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angular',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='angular',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='angular',
            name='image_url',
        ),
    ]
