# Generated by Django 6.0.5 on 2026-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angular', '0027_remove_angular_image2_url_remove_angular_image3_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(choices=[('Angular Fundamentals', 'angular_fundamentals'), ('Components & Templates', 'components_templates'), ('Directives & Pipes', 'directives_pipes'), ('Dependency Injection & Services', 'dependency_injection'), ('Component Lifecycle', 'component_lifecycle'), ('Routing', 'routing'), ('Forms', 'forms'), ('HTTP & APIs', 'http'), ('RxJS', 'rxjs'), ('Signals', 'signals'), ('NgRx', 'ngrx'), ('Angular Material', 'angular_material'), ('Change Detection', 'change_detection'), ('SSR & Hydration', 'ssr_hydration'), ('Testing', 'testing'), ('Performance', 'performance'), ('Security', 'security'), ('Build & Deployment', 'build_deployment'), ('Angular Ecosystem', 'angular_ecosystem'), ('Expert Angular', 'expert_angular')], default='routing', max_length=50),
        ),
    ]
