# Generated by Django 6.0.5 on 2026-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(unique=True)),
                ('language', models.CharField(choices=[('angular', 'Angular'), ('javascript', 'JavaScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence'), ('question_design', 'Question Design')], default='angular', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('mastery', 'Mastery')], default='beginner', max_length=20)),
                ('topic', models.CharField(default='angular', max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('content_status', models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('in review', 'InReview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived'), ('completed', 'Completed'), ('in progress', 'InProgress')], default='draft', max_length=50)),
                ('programe', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('alternate_solution', models.TextField(blank=True, null=True)),
                ('code_language', models.CharField(choices=[('typescript', 'Typescript'), ('markup', 'Markup'), ('css', 'CSS'), ('javascript', 'Javascript')], default='typescript', max_length=50)),
                ('code_block_title', models.CharField(blank=True, max_length=100, null=True)),
                ('code_editor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apps_coding',
            },
        ),
    ]
