# Generated by Django 6.0.5 on 2026-06-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coding',
            old_name='code_block_title',
            new_name='code_title',
        ),
        migrations.RenameField(
            model_name='coding',
            old_name='programe',
            new_name='question',
        ),
    ]
