# Generated by Django 6.0.5 on 2026-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_rename_code_block_title_coding_code_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='language',
            field=models.CharField(choices=[('angular', 'Angular'), ('javascript', 'JavaScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence'), ('question_design', 'Question Design')], default='javascript', max_length=50),
        ),
        migrations.AlterField(
            model_name='coding',
            name='serial_number',
            field=models.CharField(default='code-01', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='topic',
            field=models.CharField(default='array method', max_length=100),
        ),
    ]
