# Generated by Django 6.0.5 on 2026-06-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_alter_coding_language_alter_coding_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coding',
            name='solution',
            field=models.TextField(default="<p class='answer-text'>test</p>"),
        ),
    ]
