# Generated by Django 6.0.5 on 2026-06-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_alter_coding_serial_number_alter_coding_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
