# Generated by Django 6.0.5 on 2026-06-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_alter_coding_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='code_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coding',
            name='code_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
