# Generated by Django 6.0.5 on 2026-06-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_coding_code_explanation_coding_code_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coding',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CodingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_language', models.CharField(choices=[('typescript', 'Typescript'), ('markup', 'Markup'), ('css', 'CSS'), ('javascript', 'Javascript')], default='typescript', max_length=50)),
                ('code_title', models.CharField(max_length=100)),
                ('code_editor', models.TextField()),
                ('code_output', models.TextField(blank=True, null=True)),
                ('code_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='coding.coding')),
            ],
            options={
                'db_table': 'apps_coding_example',
                'ordering': ['created_at'],
            },
        ),
    ]
