# Generated by Django 6.0.5 on 2026-06-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_alter_coding_options_codingexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingexample',
            name='coding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_examples', to='coding.coding'),
        ),
    ]
