# Generated by Django 6.0.5 on 2026-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_alter_codingexample_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='code_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingexample',
            name='code_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
