LABEL_CHOICES = [
    ("beginner", "Beginner"),
    ("intermediate", "Intermediate"),
    ("advanced", "Advanced"),
    # optional extras
    ("expert", "Expert"),
    ("mastery", "Mastery"),
]


#! this is not in use, I will use this angular topic latter


TOPICS_CHOICES = [
    ("Angular Fundamentals", "angular_fundamentals"),
    ("Components & Templates", "components_templates"),
    ("Directives & Pipes", "directives_pipes"),
    ("Dependency Injection & Services", "dependency_injection"),
    ("Component Lifecycle", "component_lifecycle"),
    ("Routing", "routing"),
    ("Forms", "forms"),
    ("HTTP & APIs", "http"),
    ("RxJS", "rxjs"),
    ("Signals", "signals"),
    ("State Management", "state_management"),
    ("Angular Material", "angular_material"),
    ("Advanced Angular", "advanced_angular"),
    ("SSR & Hydration", "ssr_hydration"),
    ("Testing", "testing"),
    ("Performance", "performance"),
    ("Security", "security"),
    ("Build & Deployment", "build_deployment"),
    ("Angular Ecosystem", "angular_ecosystem"),
    ("Expert Angular", "expert_angular"),
]

TOPIC_CHOICES1 = [
    ("components", "Components"),
    ("modules", "Modules"),
    ("templates", "Templates"),
    ("data_binding", "Data Binding"),
    ("directives", "Directives"),
    ("pipes", "Pipes"),
    ("services", "Services"),
    ("dependency_injection", "Dependency Injection"),
    ("routing", "Routing"),
    ("reactive_forms", "Reactive Forms"),
    ("template_forms", "Template Driven Forms"),
    ("http", "HTTP / APIs"),
    ("observables", "Observables"),
    ("rxjs", "RxJS"),
    ("state_management", "State Management"),
    ("ngrx", "NgRx"),
    ("signals", "Signals"),
    ("change_detection", "Change Detection"),
    ("lazy_loading", "Lazy Loading"),
    ("a11y", "Accessibility"),
    ("animations", "Animations"),
    ("performance", "Performance"),
    ("ssr", "Server Side Rendering"),
    ("pwa", "PWA"),
    ("unit_testing", "Unit Testing"),
    ("e2e_testing", "E2E Testing"),
    ("angular_cli", "Angular CLI"),
    ("architecture", "Architecture"),
    ("ng_standalone", "Standalone Components"),
    ("library_dev", "Library Development"),
    ("i18n", "Internationalization"),
    ("security", "Security"),
]
