LABEL_CHOICES = [
    ("beginner", "Beginner"),
    ("intermediate", "Intermediate"),
    ("advanced", "Advanced"),
    # optional extras
    ("expert", "Expert"),
    ("mastery", "Mastery"),
]


#! this is not in use, I will use this angular topic latter


TOPICS_CHOICES = [
    ("Angular Fundamentals", "angular_fundamentals"),
    ("Components & Templates", "components_templates"),
    ("Directives & Pipes", "directives_pipes"),
    ("Dependency Injection & Services", "dependency_injection"),
    ("Component Lifecycle", "component_lifecycle"),
    ("Routing", "routing"),
    ("Forms", "forms"),
    ("HTTP & APIs", "http"),
    ("RxJS", "rxjs"),
    ("Signals", "signals"),
    ("NgRx", "ngrx"),
    ("Angular Material", "angular_material"),
    ("Change Detection", "change_detection"),
    ("SSR & Hydration", "ssr_hydration"),
    ("Testing", "testing"),
    ("Performance", "performance"),
    ("Security", "security"),
    ("Build & Deployment", "build_deployment"),
    ("Angular Ecosystem", "angular_ecosystem"),
    ("Expert Angular", "expert_angular"),
]

JAVASCRIPT_TOPICS_CHOICES = [
    ("javascript_fundamentals", "JavaScript Fundamentals"),
    ("control_flow", "Control Flow"),
    ("functions", "Functions"),
    ("scope_closures", "Scope & Closures"),
    ("objects", "Objects"),
    ("arrays", "Arrays"),
    ("strings", "Strings"),
    ("numbers_math", "Numbers & Math"),
    ("dates_time", "Dates & Time"),
    ("error_handling", "Error Handling"),
    ("es6_features", "ES6+ Features"),
    ("classes_oop", "Classes & OOP"),
    ("prototypes_inheritance", "Prototypes & Inheritance"),
    ("asynchronous_javascript", "Asynchronous JavaScript"),
    ("modules", "Modules"),
    ("dom_manipulation", "DOM Manipulation"),
    ("events", "Events"),
    ("browser_apis", "Browser APIs"),
    ("timers", "Timers"),
    ("storage", "Storage"),
    ("networking", "Networking"),
    ("web_apis", "Web APIs"),
    ("javascript_runtime", "JavaScript Runtime"),
    ("advanced_functions", "Advanced Functions"),
    ("advanced_javascript_concepts", "Advanced JavaScript Concepts"),
    ("memory_management", "Memory Management"),
    ("performance_optimization", "Performance Optimization"),
    ("security", "Security"),
    ("testing", "Testing"),
    ("design_patterns", "Design Patterns"),
    ("functional_programming", "Functional Programming"),
    ("modern_javascript_ecosystem", "Modern JavaScript Ecosystem"),
    ("javascript_browser", "JavaScript in the Browser"),
    ("typescript_for_javascript", "TypeScript for JavaScript Developers"),
    ("interview_coding_topics", "Interview & Coding Topics"),
    ("others", "Others"),
]


TOPIC_CHOICES1 = [
    ("components", "Components"),
    ("modules", "Modules"),
    ("templates", "Templates"),
    ("data_binding", "Data Binding"),
    ("directives", "Directives"),
    ("pipes", "Pipes"),
    ("services", "Services"),
    ("dependency_injection", "Dependency Injection"),
    ("routing", "Routing"),
    ("reactive_forms", "Reactive Forms"),
    ("template_forms", "Template Driven Forms"),
    ("http", "HTTP / APIs"),
    ("observables", "Observables"),
    ("rxjs", "RxJS"),
    ("state_management", "State Management"),
    ("ngrx", "NgRx"),
    ("signals", "Signals"),
    ("change_detection", "Change Detection"),
    ("lazy_loading", "Lazy Loading"),
    ("a11y", "Accessibility"),
    ("animations", "Animations"),
    ("performance", "Performance"),
    ("ssr", "Server Side Rendering"),
    ("pwa", "PWA"),
    ("unit_testing", "Unit Testing"),
    ("e2e_testing", "E2E Testing"),
    ("angular_cli", "Angular CLI"),
    ("architecture", "Architecture"),
    ("ng_standalone", "Standalone Components"),
    ("library_dev", "Library Development"),
    ("i18n", "Internationalization"),
    ("security", "Security"),
]
