# Generated by Django 6.0.5 on 2026-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Javascript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='01', max_length=100, unique=True)),
                ('language', models.CharField(choices=[('angular', 'Angular'), ('javascript', 'JavaScript'), ('ngrx', 'NgRx'), ('rxjs', 'RxJS'), ('signals', 'Signals'), ('hr', 'HR'), ('ai', 'Artificial Intelligence'), ('question_design', 'Question Design')], default='javascript', max_length=50)),
                ('label', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('mastery', 'Mastery')], default='beginner', max_length=20)),
                ('topic', models.CharField(default='javascript', max_length=100)),
                ('content_status', models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('in review', 'InReview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('archived', 'Archived'), ('completed', 'Completed'), ('in progress', 'InProgress')], default='draft', max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('code_block', models.TextField(blank=True, null=True)),
                ('code_block2', models.TextField(blank=True, null=True)),
                ('code_block3', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image2_url', models.URLField(blank=True, null=True)),
                ('image3_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('javascript_questions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_javascript',
            },
        ),
    ]
