# Generated by Django 6.0.5 on 2026-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='javascript',
            name='code_block_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javascript',
            name='code_block_title2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javascript',
            name='code_block_title3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='javascript',
            name='code_language',
            field=models.CharField(choices=[('typescript', 'Typescript'), ('markup', 'Markup'), ('css', 'CSS'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
        migrations.AddField(
            model_name='javascript',
            name='code_language2',
            field=models.CharField(choices=[('typescript', 'Typescript'), ('markup', 'Markup'), ('css', 'CSS'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
        migrations.AddField(
            model_name='javascript',
            name='code_language3',
            field=models.CharField(choices=[('typescript', 'Typescript'), ('markup', 'Markup'), ('css', 'CSS'), ('javascript', 'Javascript')], default='typescript', max_length=50),
        ),
    ]
