# Generated by Django 6.0.5 on 2026-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0002_javascript_code_block_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='topic',
            field=models.CharField(choices=[('javascript_fundamentals', 'JavaScript Fundamentals'), ('control_flow', 'Control Flow'), ('functions', 'Functions'), ('scope_closures', 'Scope & Closures'), ('objects', 'Objects'), ('arrays', 'Arrays'), ('strings', 'Strings'), ('numbers_math', 'Numbers & Math'), ('dates_time', 'Dates & Time'), ('error_handling', 'Error Handling'), ('es6_features', 'ES6+ Features'), ('classes_oop', 'Classes & OOP'), ('prototypes_inheritance', 'Prototypes & Inheritance'), ('asynchronous_javascript', 'Asynchronous JavaScript'), ('modules', 'Modules'), ('dom_manipulation', 'DOM Manipulation'), ('events', 'Events'), ('browser_apis', 'Browser APIs'), ('timers', 'Timers'), ('storage', 'Storage'), ('networking', 'Networking'), ('web_apis', 'Web APIs'), ('javascript_runtime', 'JavaScript Runtime'), ('advanced_functions', 'Advanced Functions'), ('advanced_javascript_concepts', 'Advanced JavaScript Concepts'), ('memory_management', 'Memory Management'), ('performance_optimization', 'Performance Optimization'), ('security', 'Security'), ('testing', 'Testing'), ('design_patterns', 'Design Patterns'), ('functional_programming', 'Functional Programming'), ('modern_javascript_ecosystem', 'Modern JavaScript Ecosystem'), ('javascript_browser', 'JavaScript in the Browser'), ('typescript_for_javascript', 'TypeScript for JavaScript Developers'), ('interview_coding_topics', 'Interview & Coding Topics')], default='routing', max_length=50),
        ),
    ]
