# Generated by Django 6.0.5 on 2026-06-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javascript', '0004_remove_javascript_image2_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block',
            new_name='code_editor',
        ),
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block2',
            new_name='code_editor2',
        ),
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block3',
            new_name='code_editor3',
        ),
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block_title',
            new_name='code_title',
        ),
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block_title2',
            new_name='code_title2',
        ),
        migrations.RenameField(
            model_name='javascript',
            old_name='code_block_title3',
            new_name='code_title3',
        ),
    ]
